ALTER TABLE pets ADD COLUMN IF NOT EXISTS rarity TEXT NOT NULL DEFAULT 'common';
ALTER TABLE pets ADD COLUMN IF NOT EXISTS species TEXT NOT NULL DEFAULT 'cat';
ALTER TABLE pets ADD COLUMN IF NOT EXISTS stats JSONB NOT NULL DEFAULT '{}';
ALTER TABLE pets ADD COLUMN IF NOT EXISTS backstory TEXT NOT NULL DEFAULT '';
ALTER TABLE pets ADD COLUMN IF NOT EXISTS initial_curiosity TEXT NOT NULL DEFAULT '';
